### ISSUE TITLE
Dollar signs not showing in Trader UI

### ISSUE THREAD

**Issue by jwalcorn** [IBMStockTrader/trader#19]
We used to have dollar signs whenever currency values were shown in the Trader microservice's UI.  Now they are missing.  I suspect this might be due to when we switched over to using JSPs, since that's a special symbol to the JSP processor.  Need to figure out whatever we need to do, like perhaps escaping the dollar signs, to get them to appear again.

**Comment by gasgithub** [comment]
fixed in the PR https://github.com/IBMStockTrader/trader/pull/20

**Comment by jwalcorn** [comment]
Confirmed it's fixed.  Thanks!
