### ISSUE TITLE
issues with being logged out frequently

### ISSUE THREAD

**Issue by linsun** [IBMStockTrader/trader#5]
While playing with trade (could be also because I'm playing with trade v1 and v2), I got logged out frequently even when I didn't click on the logout button.  

I ended up setting logoutOnHttpSessionExpire and trackLoggedOutSSOCookies to false, and this issue seem to go away.

**Comment by jwalcorn** [comment]
Updated server.xml to set those two fields to false.  Thanks for the feedback!
